from enum import Enum


class JobStatus(str, Enum):
    CREATED = "CREATED"
    TRANSCRIBING = "TRANSCRIBING"
    TRANSCRIBED = "TRANSCRIBED"
    DRAFT_GENERATING = "DRAFT_GENERATING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    REVISING = "REVISING"
    APPROVED = "APPROVED"
    EXPORTING = "EXPORTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
